version: '3.7'

services:
  web:
    build: ./web
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: kartoza/postgis:12.1
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=postgres

volumes:
  postgres_data: