# Generated by Django 3.0.7 on 2021-04-26 12:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_lb_nom', models.CharField(max_length=20)),
                ('generation', models.CharField(max_length=20)),
                ('statut', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('sous_operator', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, max_length=250)),
                ('forfait', models.FloatField()),
                ('link', models.URLField(blank=True, max_length=250)),
            ],
        ),
    ]
